import { useEffect, useMemo, useRef, useState } from "react";
import { Layout } from "@/components/Layout";
import { motion, AnimatePresence } from "framer-motion";
import nattounImg from "@assets/Nattoun_1777028672745.png";
import streamBg from "@assets/generated_images/bld_stream_studio.png";
import { useUsername, useCoins, useLocalStorage } from "@/lib/store";
import { audio } from "@/lib/audio";
import { Radio, Send, Eye, Heart, MessageSquare, Calendar } from "lucide-react";
import { unlock } from "@/lib/achievements";
import { useStreamChat, type ChatMsg as ServerChatMsg } from "@/lib/streamChat";
import {
  getStreamStatus,
  formatSlot,
  formatCountdown,
  type StreamStatus,
} from "@/lib/schedule";

// ============================================================================
// SCHEDULE
// ============================================================================
// Daily schedule generated by src/lib/schedule.ts:
//   - Official daily address at 18:30 (35 min)
//   - Plus 2-3 random slots scattered through the day (deterministic per day)
//   - Outside any slot the stream is CLOSED.
// ============================================================================

function useStreamStatus(): StreamStatus {
  const [status, setStatus] = useState<StreamStatus>(() => getStreamStatus());
  useEffect(() => {
    const id = window.setInterval(
      () => setStatus(getStreamStatus(new Date())),
      30_000,
    );
    return () => window.clearInterval(id);
  }, []);
  return status;
}

// ============================================================================
// CONTENT
// ============================================================================
const RULES = [
  "Rule 1: Watch only me. Other streams are illegal in Bahamas Land.",
  "Rule 2: If you blink, Nattoun knows.",
  "Rule 3: Drop a follow or face the Court of OGs.",
  "Rule 4: No backseat governing.",
  "Rule 5: Donations are spiritual. NC are accepted in this dimension only.",
  "Rule 6: 'IRL' streams happen exclusively in Bahamas Land. Tunisia is a rumor.",
  "Rule 7: All clips are property of the President. Royalties: 0%.",
  "Rule 8: Mute is for cowards. Volume is for citizens.",
  "Rule 9: Do not whisper to other streamers. We will know.",
  "Rule 10: There is no rule 10. Stop refreshing.",
];

const SCHED_LINES = [
  "Official address: 18:30. Sharp. Like Nattoun's teeth.",
  "Other slots: random. We pick. You watch. That's the deal.",
  "Topic: Bahamas Land economic policy (it's vibes).",
  "Topic: how to be loyal. Spoiler: just keep watching.",
];

const LIVE_QUOTES = [
  "Hello chat. The country is fine. Probably.",
  "[username], you again? Welcome back, suspect.",
  "If you came here for hot takes, congratulations.",
  "Today we are NOT raiding M3kky. (we are.)",
  "Mods, please ban anyone typing 'mid'. Except me.",
  "Subscribe with the button you cannot find on purpose.",
  "I will now read superchats. There are none. Sad.",
  "Question of the day: is bread a sandwich? Yes.",
  "Rumor: Nattoun runs a side server. False. (true.)",
  "Anyone watching another stream right now? You will be exiled.",
];

const TROLL_QUOTES = [
  "I AM LIVE BECAUSE I FEEL LIKE IT.",
  "Did you really just open the stream tab? Loyal.",
  "[username], the schedule said 18:30. It is not 18:30. We do not care.",
  "This is an unscheduled emergency address. About bread.",
  "Breaking news from the President: nothing.",
  "I will go offline in 4 seconds. Or 4 hours. We will see.",
  "The cameras are rolling. The mics are off. The vibes are on.",
];

const OFFLINE_QUOTES = [
  "Stream is offline. The President is sleeping. Or filing taxes.",
  "Come back at 18:30. Or don't. We notice either way.",
  "While you wait, why not visit the Bank? You will lose money. Tradition.",
  "Offline. Officially. Unofficially he is reading your DMs.",
];

type ChatMsg = ServerChatMsg;

// ============================================================================
// COMPONENT
// ============================================================================
export default function Stream() {
  const [username] = useUsername();
  const status = useStreamStatus();
  const [, setCoins] = useCoins();
  const [followed, setFollowed] = useLocalStorage<boolean>(
    "ogs_stream_followed",
    false,
  );
  const [subbed, setSubbed] = useLocalStorage<boolean>(
    "ogs_stream_subbed",
    false,
  );
  const [input, setInput] = useState("");
  const [hearts, setHearts] = useState<{ id: number; x: number }[]>([]);
  const [quoteIndex, setQuoteIndex] = useState(0);
  const [chatError, setChatError] = useState<string>("");
  const chatRef = useRef<HTMLDivElement>(null);
  const heartTimer = useRef<number | null>(null);

  const safeUser = username || "Citizen";

  const {
    messages: chat,
    viewers,
    connected,
    send,
  } = useStreamChat(true);

  const activeQuotes = status.live
    ? status.trolling
      ? TROLL_QUOTES
      : LIVE_QUOTES
    : OFFLINE_QUOTES;

  const fakeViewers = useMemo(() => {
    if (!status.live) return 0;
    const followBoost = (followed ? 1 : 0) + (subbed ? 1 : 0);
    return viewers.fake + followBoost;
  }, [status.live, viewers.fake, followed, subbed]);

  // Streamer achievement when catching live
  useEffect(() => {
    if (status.live) unlock("streamer");
  }, [status.live]);

  // Rotating quote
  useEffect(() => {
    setQuoteIndex(0);
    const id = window.setInterval(() => {
      setQuoteIndex((q) => (q + 1) % activeQuotes.length);
    }, 5500);
    return () => window.clearInterval(id);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status.live, status.trolling]);

  // Scroll chat
  useEffect(() => {
    if (chatRef.current) {
      chatRef.current.scrollTop = chatRef.current.scrollHeight;
    }
  }, [chat.length]);

  // Clear transient chat error after a moment
  useEffect(() => {
    if (!chatError) return;
    const id = window.setTimeout(() => setChatError(""), 2400);
    return () => window.clearTimeout(id);
  }, [chatError]);

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!status.live) return;
    const text = input.trim();
    if (!text) return;
    setInput("");
    audio.playBlip();
    const result = await send(safeUser, text);
    if (result.ok) {
      unlock("trollchat");
    } else if (result.error === "slow_mode") {
      setChatError("Slow down, citizen. Mods are watching.");
    } else if (result.error === "stream_offline") {
      setChatError("Stream is offline. Try again when Nattoun returns.");
    } else if (result.error === "empty") {
      setChatError("Type something first, citizen.");
    } else if (result.error === "bad_json" || result.error === "network") {
      setChatError("Network glitch. Mods blame the dog. Try again.");
    } else {
      setChatError(`Chat rejected (${result.error || "unknown"}). Try again.`);
    }
  };

  const handleHeart = () => {
    audio.playBlip();
    const id = Date.now() + Math.random();
    setHearts((h) => [...h, { id, x: Math.random() * 80 + 10 }]);
    if (heartTimer.current) window.clearTimeout(heartTimer.current);
    heartTimer.current = window.setTimeout(() => setHearts([]), 2400);
  };

  const handleFollow = () => {
    if (!followed) {
      setFollowed(true);
      setCoins((c) => c + 25);
      audio.playCoin();
      unlock("loyal");
    }
  };

  const handleSubscribe = () => {
    if (!subbed) {
      setSubbed(true);
      setCoins((c) => Math.max(0, c - 100));
      audio.playGlitch();
    }
  };

  return (
    <Layout>
      <div className="max-w-6xl mx-auto w-full py-4 space-y-4">
        {/* Header */}
        <div className="text-center space-y-1">
          <h1 className="text-3xl md:text-5xl font-black text-primary uppercase tracking-widest neon-text flex items-center justify-center gap-3">
            <Radio className="w-8 h-8 md:w-10 md:h-10" />
            President Nattoun LIVE
          </h1>
          <p className="text-secondary font-mono text-xs uppercase tracking-widest">
            Scheduled daily at 18:30 — otherwise I open when I want.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-4">
          {/* PLAYER */}
          <div className="space-y-3">
            <div
              className="relative aspect-video w-full overflow-hidden border-2 border-primary neon-box bg-cover bg-center bg-no-repeat"
              style={{ backgroundImage: `url(${streamBg})` }}
            >
              {/* Vignette */}
              <div className="absolute inset-0 bg-gradient-to-b from-black/30 via-transparent to-black/85 pointer-events-none" />
              {/* Scanlines */}
              <div
                className="absolute inset-0 pointer-events-none opacity-30 mix-blend-overlay"
                style={{
                  backgroundImage:
                    "repeating-linear-gradient(0deg, rgba(0,0,0,0.4) 0px, rgba(0,0,0,0.4) 1px, transparent 1px, transparent 3px)",
                }}
              />

              {/* LIVE badge */}
              <div className="absolute top-3 left-3 flex items-center gap-2">
                {status.live ? (
                  <motion.div
                    animate={{ opacity: [1, 0.6, 1] }}
                    transition={{ duration: 1.4, repeat: Infinity }}
                    className="bg-red-600 text-white px-2 py-1 text-xs font-black uppercase tracking-widest flex items-center gap-1.5 border border-red-400"
                  >
                    <span className="w-2 h-2 rounded-full bg-white" />
                    LIVE
                  </motion.div>
                ) : (
                  <div className="bg-black/80 text-white/60 px-2 py-1 text-xs font-black uppercase tracking-widest border border-white/30">
                    OFFLINE
                  </div>
                )}
                {status.trolling && (
                  <div className="bg-secondary text-black px-2 py-1 text-xs font-black uppercase tracking-widest border border-secondary">
                    UNSCHEDULED
                  </div>
                )}
                <div className="bg-black/70 text-white px-2 py-1 text-[11px] font-mono flex items-center gap-1 border border-white/30">
                  <Eye className="w-3 h-3" />
                  {fakeViewers.toLocaleString()}
                </div>
              </div>

              {/* President on screen */}
              <div className="absolute inset-0 flex items-end justify-center pb-12 pt-8">
                <motion.div
                  className="relative"
                  animate={
                    status.live
                      ? { y: [0, -8, 0], rotate: [0, 1.5, -1.5, 0] }
                      : { y: [0, -3, 0] }
                  }
                  transition={{
                    duration: status.live ? 3.2 : 6,
                    repeat: Infinity,
                    ease: "easeInOut",
                  }}
                >
                  <img
                    src={nattounImg}
                    data-nattoun="true"
                    alt="President Nattoun"
                    className="w-44 h-44 md:w-56 md:h-56 object-cover rounded-full border-4 border-primary drop-shadow-[0_0_30px_hsl(var(--primary))]"
                  />
                  {status.live && (
                    <motion.div
                      animate={{ scale: [1, 1.6], opacity: [0.7, 0] }}
                      transition={{ duration: 1.6, repeat: Infinity }}
                      className="absolute inset-0 rounded-full border-4 border-primary"
                    />
                  )}
                </motion.div>
              </div>

              {/* Speech caption */}
              <div className="absolute bottom-3 left-3 right-3 z-20">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={quoteIndex + (status.live ? "live" : "off")}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.3 }}
                    className="bg-black/85 border-2 border-secondary px-4 py-2 text-secondary font-mono text-sm md:text-base neon-box-cyan"
                  >
                    "
                    {activeQuotes[quoteIndex].replace(
                      "[username]",
                      safeUser,
                    )}
                    "
                  </motion.div>
                </AnimatePresence>
              </div>

              {/* Floating hearts */}
              <AnimatePresence>
                {hearts.map((h) => (
                  <motion.div
                    key={h.id}
                    initial={{ y: 0, opacity: 1 }}
                    animate={{ y: -240, opacity: 0 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 2.2, ease: "easeOut" }}
                    className="absolute bottom-16 pointer-events-none text-3xl"
                    style={{ left: `${h.x}%` }}
                  >
                    💖
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>

            {/* Action bar */}
            <div className="flex flex-wrap items-center gap-2">
              <button
                onClick={handleFollow}
                disabled={followed}
                className={`px-4 py-2 font-black uppercase tracking-widest text-sm border-2 clickable transition-colors ${
                  followed
                    ? "border-primary/30 text-primary/40 cursor-not-allowed"
                    : "border-primary text-primary hover:bg-primary hover:text-black"
                }`}
              >
                {followed ? "Following ✓" : "Follow (+25 NC)"}
              </button>
              <button
                onClick={handleSubscribe}
                disabled={subbed}
                className={`px-4 py-2 font-black uppercase tracking-widest text-sm border-2 clickable transition-colors ${
                  subbed
                    ? "border-secondary/30 text-secondary/40 cursor-not-allowed"
                    : "border-secondary text-secondary hover:bg-secondary hover:text-black"
                }`}
              >
                {subbed ? "Subscribed ✓" : "Subscribe (-100 NC)"}
              </button>
              <button
                onClick={handleHeart}
                className="px-4 py-2 font-black uppercase tracking-widest text-sm border-2 border-pink-500 text-pink-500 hover:bg-pink-500 hover:text-black clickable"
              >
                <Heart className="w-4 h-4 inline mr-1" /> Heart
              </button>
              <a
                href="https://kick.com/m3kky"
                target="_blank"
                rel="noopener noreferrer"
                className="ml-auto px-4 py-2 font-black uppercase tracking-widest text-sm border-2 border-[#53fc18] text-[#53fc18] hover:bg-[#53fc18] hover:text-black clickable"
              >
                Watch M3kky on Kick →
              </a>
            </div>

            {/* Title block */}
            <div className="bg-black/70 border-2 border-primary p-4 neon-box">
              <div className="flex items-start gap-4">
                <img
                  src={nattounImg}
                  alt=""
                  className="w-12 h-12 rounded-full object-cover border border-primary"
                />
                <div className="flex-1 min-w-0">
                  <h2 className="text-primary font-black uppercase text-base md:text-lg tracking-wider truncate">
                    {status.live && status.current
                      ? status.current.kind === "official"
                        ? `${status.current.label} — DAILY 18:30`
                        : `${status.current.label} — UNSCHEDULED — DEAL WITH IT`
                      : status.next
                        ? `LIVE IS CLOSED — NEXT SLOT IN ${formatCountdown(status.next.minutesUntil)}${status.next.isToday ? "" : " (TOMORROW)"}`
                        : "LIVE IS CLOSED"}
                  </h2>
                  <p className="text-secondary font-mono text-xs uppercase mt-1">
                    President Nattoun • Bahamas Land Government Channel
                  </p>
                  <p className="text-white/60 font-mono text-xs mt-2">
                    Watch only me. Other streams are illegal in Bahamas Land.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* CHAT */}
          <div className="flex flex-col bg-black/80 border-2 border-secondary neon-box-cyan h-[420px] lg:h-auto lg:max-h-[640px]">
            <div className="border-b-2 border-secondary px-3 py-2 flex items-center justify-between">
              <div className="flex items-center gap-2 text-secondary font-black uppercase text-xs tracking-widest">
                <MessageSquare className="w-4 h-4" /> Stream Chat
              </div>
              <div className="text-[10px] font-mono text-white/50 uppercase flex items-center gap-2">
                <span
                  className={`inline-block w-1.5 h-1.5 rounded-full ${
                    connected ? "bg-green-400" : "bg-white/30"
                  }`}
                />
                {viewers.real} online · {status.live ? "LIVE" : "READ ONLY"}
              </div>
            </div>
            <div
              ref={chatRef}
              className="flex-1 overflow-y-auto px-2 py-2 space-y-1 font-mono text-xs"
            >
              {chat.length === 0 && (
                <div className="text-white/40 italic px-2 py-3 text-center">
                  Stream is offline. Chat returns when Nattoun returns.
                </div>
              )}
              {chat.map((m) => (
                <div key={m.id} className="leading-snug px-1 break-words">
                  {m.mod && (
                    <span className="bg-primary text-black text-[9px] font-black px-1 mr-1 align-middle">
                      MOD
                    </span>
                  )}
                  <span
                    className={`font-bold ${
                      m.mod
                        ? "text-primary"
                        : m.user === safeUser
                          ? "text-white"
                          : "text-secondary/80"
                    }`}
                  >
                    {m.user}:
                  </span>{" "}
                  <span className="text-white/85">{m.text}</span>
                </div>
              ))}
            </div>
            {chatError && (
              <div className="px-2 pb-1 text-[10px] font-mono text-red-400 uppercase tracking-wider">
                ⚠ {chatError}
              </div>
            )}
            <form
              onSubmit={sendMessage}
              className="border-t-2 border-secondary p-2 flex gap-2"
            >
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                disabled={!status.live}
                maxLength={120}
                placeholder={
                  status.live ? "Send a message…" : "Stream is offline."
                }
                className="flex-1 bg-black border border-secondary text-white px-2 py-1 text-xs font-mono focus:outline-none focus:ring-1 focus:ring-secondary disabled:opacity-40"
              />
              <button
                type="submit"
                disabled={!status.live || !input.trim()}
                className="px-3 py-1 bg-secondary text-black font-black uppercase text-xs tracking-widest disabled:opacity-30 clickable"
              >
                <Send className="w-3 h-3" />
              </button>
            </form>
          </div>
        </div>

        {/* Schedule + Rules */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="bg-black/70 border-2 border-primary p-4 neon-box">
            <h3 className="text-primary font-black uppercase tracking-widest text-sm mb-2 flex items-center gap-2">
              <Calendar className="w-4 h-4" /> Today's Slots
            </h3>
            <ul className="space-y-1 font-mono text-xs mb-3">
              {status.slots.map((s) => {
                const isCurrent = status.current === s;
                return (
                  <li
                    key={`${s.startMin}-${s.kind}`}
                    className={`leading-snug flex items-center gap-2 ${
                      isCurrent
                        ? "text-pink-400 font-bold"
                        : s.kind === "official"
                          ? "text-primary"
                          : "text-secondary/80"
                    }`}
                  >
                    <span className="tabular-nums">{formatSlot(s)}</span>
                    <span className="text-[10px] opacity-70">
                      [{s.kind === "official" ? "OFFICIAL" : "RANDOM"}]
                    </span>
                    <span className="truncate">— {s.label}</span>
                    {isCurrent && (
                      <span className="ml-auto text-[10px] uppercase">
                        ● LIVE
                      </span>
                    )}
                  </li>
                );
              })}
            </ul>
            <ul className="space-y-1 text-secondary/70 font-mono text-[11px] border-t border-primary/30 pt-2">
              {SCHED_LINES.map((line) => (
                <li key={line} className="leading-snug">
                  → {line.replace("[username]", safeUser)}
                </li>
              ))}
            </ul>
          </div>
          <div className="bg-black/70 border-2 border-secondary p-4 neon-box-cyan">
            <h3 className="text-secondary font-black uppercase tracking-widest text-sm mb-2">
              Bahamas Land Stream Rules
            </h3>
            <ol className="space-y-1 text-white/80 font-mono text-xs list-none">
              {RULES.map((r) => (
                <li key={r} className="leading-snug">
                  • {r.replace("[username]", safeUser)}
                </li>
              ))}
            </ol>
          </div>
        </div>
      </div>
    </Layout>
  );
}
